### PR TITLE
fix: make alphabetical order work in search engine

### LINKED ISSUE #882: Software catalogue: sort by alphabetical order doesn't work
**Describe the bug**
Sort by alphabetical order doesn't work 

**To Reproduce**
1. Go to https://developers.italia.it/en/search
2. Sort by 'Alphabetical'
3. Items are not sorted properly

### PR DESCRIPTION
**Pull request by bfabio**
Use Elastic's scripting to sort alphabetically and provide a fallback if
localizedName for the current language is not present.
    
I don't know if that's the smartest way to do it, but it's A solution.

Fix #882

### CODE REVIEW

**Comment by developers-italia-droid** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>There is a problem with the commit message
> (alternative) use Elasticsearch scripting
- subject may not be empty
- type may not be empty</td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against cc16b52a22ef3cc0115087e4216e262d2f8f522c
</p>

File: assets/js/api/elasticSearchUtils.js [hunk 1]
```diff
@@ -18,11 +18,26 @@ export const buildFilter = (filters) => {
...
-        'publiccode.description.it.localizedName.keyword': { order: 'asc', unmapped_type: 'keyword' },
+    return {
+      _script: {
+        type: 'string',
+        order: 'asc',
+        script: {
+          lang: 'painless',
+          source: `
+             if (
+                 doc['publiccode.description.it.localisedName.keyword'].size() != 0
```
Comment (sebbalex) [inline assets/js/api/elasticSearchUtils.js:29]: I'm personally against this kind of manipulation but it can be useful to have current language as a parameter and fallback (as already done) whether it is not present in publiccode. wdyt?

**Comment by bfabio** [comment]
@sebbalex oops, it was missing the part where the query is constructed dynamically.
