### PR TITLE
Fix alphabetical order breaking the search.

### LINKED ISSUE #650: Alphabetical ordering in the search engine doesn't work
**Describe the bug**
When you try to alphabetically order the search results the site shows no results at all:

Peek 07-09-2020 19-27

### PR DESCRIPTION
**Pull request by bfabio**
Fix alphabetical order breaking the search. This works just for
Italian for now.

Fix #650.

See also italia/developers-italia-backend#201

### CODE REVIEW

**Comment by bfabio** [comment]
@sebbalex This is not ideal, being just for Italian and all, but I think we shouldn't waste too much time here given that the search engine will be refactored.

**Comment by sebbalex** [comment]
What if we just create an alias directly in Elasticsearch mapping model that will points to desired fields, will avoid [this](https://github.com/italia/developers-italia-backend/pull/201#issuecomment-708297039) also. Wdyt @bfabio ?

File: assets/js/esDevelopersItaliaQuery.js [hunk 1]
```diff
@@ -655,15 +655,15 @@ esDevelopersItaliaQuery.prototype.getSortQuery = function () {
 
   switch (value) {
     case 'az':
-      sort.push({
-        'name.raw': { 'order': 'asc' }
-      });
+      sort.push(
+        { 'publiccode.description.it.localizedName.keyword': { 'order': 'asc', unmapped_type: 'keyword' } },
```
Comment (sebbalex) [inline assets/js/esDevelopersItaliaQuery.js:659]: do we still need `unmapped_type`?

Comment (bfabio) [reply assets/js/esDevelopersItaliaQuery.js:659]: We do because the query / filtering can be performed against indexes that don't have that particular mapping (eg. administrations, platforms). That happens when the search page returned multiple types and you want to filter on those. 

With no `unmapped_type`, the missing mapping error makes all the results from that index disappear. We need more work in the future to have those actually sorted though.

Comment (sebbalex) [reply assets/js/esDevelopersItaliaQuery.js:659]: got it :+1:

**Review by sebbalex — APPROVED** [review]
